src/pipeline.yaml

testsuite now uses kubectl binary instead of openshift's oc
also changed cluster auth flow to [Implicit Grant](https://datatracker.ietf.org/doc/html/rfc6749#section-4.2) for compatibility with kubectl

Change cluster login from oc to kubectl

---

main/pipeline.yaml
nightly/eventlistener.yaml
nightly/pipeline.yaml

Make upload-results task optional

---

main/pipeline.yaml
nightly/eventlistener.yaml
nightly/pipeline.yaml
tasks/kubectl-login-task.yaml
tasks/run-tests-task.yaml

Add kubeconfig path parameter to run-tests task to support multiple kubeconfigs for multicluster tests
Closes #29

Run multicluster tests in the nightly pipeline

---

nightly/eventlistener.yaml

The `test` make target can take longer than default 1h timeout.
Documentation:
https://tekton.dev/docs/pipelines/pipelines/#configuring-the-failure-timeout
https://tekton.dev/docs/pipelines/pipelineruns/#configuring-a-failure-timeout
Apply the pipelines to some cluster (other than the one where nightlies rue) and validate that the timeout is set as expected

Increase timeout to 2h

---

main/pipeline.yaml
nightly/eventlistener.yaml
nightly/pipeline.yaml
tasks/run-tests-task.yaml

- Add new dnstls make target task with azure as DNS provider
- Add a feature to append pytest parameters for testsuite execution
Closes #46

Add dnstls-azure task to the nightly pipeline

---

Dockerfile
README.md
infra/delete-osd-pipeline.yaml
infra/kustomization.yaml
infra/osd-aws-pipeline.yaml
infra/osd-gcp-pipeline.yaml
tasks/infra/delete-osd-task.yaml
tasks/infra/get-osd-credentials-task.yaml
tasks/infra/kustomization.yaml
tasks/infra/ocm-login-task.yaml
tasks/infra/provision-osd-aws-task.yaml
tasks/infra/provision-osd-gcp-task.yaml
tasks/infra/wait-till-osd-is-deleted-task.yaml
tasks/infra/wait-till-osd-is-ready-task.yaml

Adds pipeline for OSD on AWS cluster creation.
`oc apply -k infra/ -n desired-ns`
One has to have secrets created in desired namespace:
`kubectl create secret generic kua-ocm-stage-client-credentials --from-literal=CLIENT_ID="xxx" --from-literal=CLIENT_SECRET="xxx" -n desired-ns`
`kubectl create secret generic kua-aws-credentials --from-literal=AWS_ACCOUNT_ID="xxx" --from-literal=AWS_ACCESS_KEY_ID="xxx" --from-literal=AWS_SECRET_ACCESS_KEY="xxx" -n desired-ns`

Pipeline to provision OSD on AWS

---

Dockerfile

The image built from this Dockerfile should replace all images used in this repository.
I changed the base image to one pulled from public repository for easier building on non-authenticated machines.
Added more tools used in other pipelines:
- helm
- rosa
- kubectl
- opm (for upcoming downstream deploy pipeline)
- buildah (for upcoming downstream deploy pipeline)
I checked the image size difference with this version and version with all commands merged into single `RUN` statement and it was identical so I kept this multiple `RUN` version for better readability.
When building the image I suggest using `--no-cache` flag to make sure the newest version of the tools is installed.

Add more tools to Dockerfile

---

Dockerfile

Add missing utility used in helm-uninstall-task
`xargs` in contained in [findutils](https://www.gnu.org/software/findutils/)
I already pushed the new Dockerfile to tag `latest` and `0.2` in [quay.io/kuadrant/testsuite-pipelines-tools](https://quay.io/repository/kuadrant/testsuite-pipelines-tools?tab=tags)

Add xargs to Dockerfile

---

README.md
deploy/pipeline-nightly-update.yaml
deploy/pipeline.yaml
main/pipeline.yaml
nightly/pipeline.yaml
tasks/login/kubectl-login-task.yaml
tasks/run-tests-task.yaml

Allow for specifying cluster credentials via input parameter.
Default value is set for `openshift-pipelines-credentials` so pipelines should continue to work as they are, no need to explicitly set the input param.
Eye review. I validated via https://console-openshift-console.apps.kua-multi-1.osp.api-qe.eng.rdu2.redhat.com/k8s/ns/trepel/tekton.dev~v1~PipelineRun/kuadrant-deploy-pipeline-1c84as/parameters where I used custom secret name to install Kuadrant via helm.

Allow for specifying cluster credentials via input parameter

---

main/pipeline.yaml
nightly/pipeline.yaml
tasks/login/kubectl-login-task.yaml
tasks/upload-results-task.yaml

Add testing cluster version label to imported launch. 
Required testsuite changes were in https://github.com/Kuadrant/testsuite/pull/646

Add ocp version and description to RP import task

---

infra/osd-aws-pipeline.yaml
infra/osd-gcp-pipeline.yaml
tasks/infra/kustomization.yaml
tasks/infra/wait-for-valid-certificates-task.yaml

OCM/HCC says 'ready' once cluster is ready but it does only mean that all the operators are up and running. It does not necessarily mean that all of the operators have actually finished their jobs.
Waiting for valid certificates to get applied is a good way for checking the cluster readiness because it usually takes the most time.
Closes https://github.com/Kuadrant/testsuite-pipelines/issues/75
Eye review. You can also check the PipelineRun CR in `trepel` ns in kua multi 1 cluster where I tested this.

Wait for valid certificates to be applied on OSD cluster

---

tasks/deploy/uninstall-task.yaml

So the "delete-kuadrant-crd" step wont get stuck if there are leftover CR's with finalizers after the operator pods get stopped.

Add remove leftovers task to helm uninstall

---

Dockerfile
README.md
infra/delete-rosa-pipeline.yaml
infra/kustomization.yaml
infra/rosa-pipeline.yaml
tasks/infra/delete-rosa-task.yaml
tasks/infra/kustomization.yaml
tasks/infra/provision-rosa-task.yaml
tasks/infra/rosa-login-task.yaml
tasks/infra/wait-till-osd-is-deleted-task.yaml

This PR adds a pipeline to provision ROSA cluster.
- updates Dockerfile to add aws v2 cli tool, it is required by rosa cli tool
- readme update, just adding a AWS secret and some info about image building
- adds two tasks (rosa login and rosa provisioning)
- the image is already updated in quay.io
The wait for ready task and get credential tasks were reused.
Eye review together with eye check of the pipeline in `trepel` ns in kua multi 1 should suffice.

Pipeline to provision ROSA

---

README.md

https://github.com/Kuadrant/testsuite-pipelines/pull/81#discussion_r2041924839
I still dont think editing managed CR directly is a good idea as it can be at any time rewritten by the operator and the changes lost. The TektonConfig should be the place for this.
I also extracted the nameserver ip addresses for easier changing, as they need to be replaced by real resolvers before executing.

Change patch in README to tektonconfig/config

---

README.md

With the increased frequency of pipelines usage, change pipelinerun pruner from "keep last 7 pipelineruns" to "keep last 7 days of runs"

Use keep-since for the pipelinerun pruner

---

README.md
dast/kustomization.yaml
dast/pipeline.yaml
tasks/dast/clone-rapidast-repo-task.yaml
tasks/dast/compose-config-file-task.yaml
tasks/dast/kustomization.yaml
tasks/dast/rapidast-cleanup-task.yaml
tasks/dast/rapidast-scan-task.yaml
tasks/dast/wait-for-job-to-complete-task.yaml
tasks/login/kubectl-login-task.yaml

This PR adds rapiDAST pipeline. It scans four custom Kubernetes APIs the Kuadrant offers and stores the result in Google Cloud Storage.
Run the pipeline or take a look at my run in `trepel` ns.

Add rapiDAST pipeline

---

dast/pipeline.yaml

DAST pipeline run rapiDAST scan via Helm. A new pod where the scan is performed is created as part of running the Helm chart. The file (containing key for scan result storage) needs to be accessible for the pod. In order to do so the Helm uses the same PVC as the pipeline (and before running Helm pipeline makes sure the file is stored in that PVC). The PVC name is then passed to Helm chart.
This means that both pipeline pod and Helm pod use the same PVC which leads to "Multi-attach" error in Helm pod (PVC is in already use by pipeline that triggered the Helm). To avoid this the DAST pipeline need to have `coschedule:workspaces` set. This allow for Helm pod to access PVC (the Task that triggers Helm is not configured to use workspace so it does not use the PVC).
Trigger the pipeline or …

Use coschedule:workspaces in DAST pipeline

---

dast/pipeline.yaml
deploy/pipeline-nightly-update.yaml
deploy/pipeline.yaml
tasks/deploy/helm-install-task.yaml

Add parameter allowing to specify any flags for Helm install command allowing to override whatever is defined in values.yaml.
What hes been done
rapiDAST version bump, a new version has been released: https://github.com/RedHatProductSecurity/rapidast/releases
`--set=kuadrant.installPlanApproval=Automatic` has been added as a default value. Reason is that empty string does not count as default value so it makes the parameter required which I did not want to. This default value effectively does nothing because it it set as Automatic in values.yaml anyway.
Refactoring the Task to use `.script` rather than `.command` and `.args`.
Run the deploy pipeline or take a look at two PipelineRuns in my ns (once the param was left empty).

Add parameter for helm install command flags

---

tasks/deploy/clone-task.yaml

Helm charts repo moved to Kuadrant org: https://github.com/Kuadrant/helm-charts-olm
The old repo path will be automatically redirected as promised here: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#whats-transferred-with-a-repository

Transfer helm chart repo

---

infra/delete-rosa-pipeline.yaml
infra/osd-aws-pipeline.yaml
infra/osd-gcp-pipeline.yaml
infra/rosa-pipeline.yaml
main/kustomization.yaml
main/provision-upgrade-test-pipeline.yaml
tasks/deploy/helm-install-task.yaml
tasks/infra/get-osd-credentials-task.yaml
tasks/infra/prepare-for-rhcl-rc-install-task.yaml
tasks/infra/provision-osd-aws-task.yaml
tasks/infra/provision-osd-gcp-task.yaml
tasks/infra/provision-rosa-task.yaml
tasks/provision-install-test/kustomization.yaml
tasks/provision-install-test/parameter-sanity-check-task.yaml
tasks/provision-install-test/upgrade-to-latest-task.yaml

Pipeline for upgrade testing.
Small description fix in rosa delete Pipeline.
Added option to skip cluster provisioning in provision-install-test Pipeline, useful if cluster already exists.
Small fix in provision-install-test Pipeline, ocm-login Task has to be done for ROSA too - OCM/HCC is used in subsequent parameter-sanity-check Task to determine ROSA version if the version is not defined explicitly via `create-cmd-params` input parameter.
Reordering steps in helm-instal Task to install Tools first due to Keycloak connection issue that happens if tests are triggered too quickly after Tools installation.
Added wait for global pull secret change to propagate to all nodes.
Added upgrade Pipeline including a new Task to trigger the upgrade to latest version and wait for it to complete. …

Add pipeline for upgrade testing

---

main/provision-install-test-pipeline.yaml
main/provision-upgrade-test-pipeline.yaml
tasks/infra/prepare-for-rhcl-rc-install-task.yaml
tasks/provision-install-test/kustomization.yaml
tasks/provision-install-test/operator-pod-restart-task.yaml

A few improvement to make the pipelines more robust and stable.
Added task to restart kuadrant operator pod after installation - it happens time to time that limitador-/authorino-/dns-oprerator is not fully ready and kuadrant operator sees that and gets stuck. Restart makes kuadrant operator reconcile properly.
Increased timeouts for applying global pull secret change - this can take quite some time sometimes.
Run the pipeline (one of the two is enough). Simpler option is to review pipeline run logs in trepe2 ns.

Hardening of full cycle pipelines

---

README.md

Adding section on how to built the image using `podman`. We should prefer `podman` to `docker` whenever possible.
Just follow the steps outlined in README.md for `podman`.

Add section on building with podman

---

deploy/pipeline-nightly-update.yaml
deploy/pipeline.yaml
main/aro-provision-install-test-pipeline.yaml
main/provision-install-test-pipeline.yaml
main/provision-upgrade-test-pipeline.yaml
tasks/infra/prepare-for-rhcl-rc-install-task.yaml

Replace space defaults with empty strings and increase MCP timeouts.
Using empty string instead of single space char is much nicer and avoid issues in contexts where single space matters (e.g. single space can be evaluated to true rather that false etc). It is also consistent with some other pipelines where we using empty string already:
* https://github.com/Kuadrant/testsuite-pipelines/blob/main/main/pipeline.yaml#L26-L42
* https://github.com/Kuadrant/testsuite-pipelines/blob/main/nightly/pipeline.yaml#L45
* https://github.com/Kuadrant/testsuite-pipelines/blob/main/release/pipeline.yaml#L26-L45
* https://github.com/Kuadrant/testsuite-pipelines/blob/main/release/pipeline.yaml#L26-L45
I also increased timeout for global pull secret change to get applied across all the nodes on the cluster. …

Replace space defaults with empty strings and increase MCP timeouts

---

pipelines/test/release/pipeline.yaml

This PR adds a `run-tests-disruptive` task to the release pipeline. It is set to run as the last `run-tests` task in the pipeline.
Tested pipeline to verify the disruptive tests ran as expected, results can be seen here: https://console-openshift-console.apps.kua-hub.osp.api-qe.eng.rdu2.redhat.com/k8s/ns/kuadrant-pipelines/tekton.dev~v1~PipelineRun/test-release-run-kwqn5/ (fyi, I set upload to false for this test run)
Closes #112

Add make disruptive task to the release pipeline

---

pipelines/test/aro/pipeline.yaml

Remove workspace from delete ARO task. This task does not require workspace at all. It is used in another pipeline without the workspace:
https://github.com/Kuadrant/testsuite-pipelines/blob/main/pipelines/infra/delete-aro/pipeline.yaml#L24-L34
Eye review, this change is simple enough, it is used like this in another pipeline, and I already applied this to kua-hub so you can take a look at
rhcl-install-aro-cleanup PipelineRun to see what issue this causes
rhcl-install-aro-cleanup-4 PipelineRun to see that this change indeed fixed the issue

Remove workspace from delete ARO task

---

pipelines/deploy/kuadrant-nightly-update/trigger-nightly-update.yaml
pipelines/test/nightly/trigger-nightly-cronjob.yaml

I forgot to change the names in cronjobs during the [refactor](https://github.com/Kuadrant/testsuite-pipelines/pull/109). Changing them now

Fix event listeners endpoints
